### PR TITLE
Demo: Change input field value following input type

### LINKED ISSUE #27: Demo: changing input math language should show the converted equation in the new language
Screenshot 2023-12-21 at 3 27 29 PM

By default the equation is in language "AsciiMath":

```
sum_(i=1)^n i^3=((n(n+1))/2)^2
```

When I change the input language to "MathML", it should show:

```

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mrow>
      <munderover>
        <mo>&#x2211;</mo>
        <mrow>
          <mi>i</mi>
          <mo>=</mo>
          <mn>1</mn>
        </mrow>
        <mi>n</mi>
      </munderover>
      <msup>
        <mi>i</mi>
        <mn>3</mn>
      </msup>
    </mrow>
    <mo>=</mo>
    <msup>
      <mrow>
        <mo>(</mo>
        <mfrac>
          <mrow>
            <mi>n</mi>
            <mrow>
              <mo>(</mo>
              <mi>n</mi>
              <mo>+</mo>
              <mn>1</mn>
              <mo>)</mo>
            </mrow>
          </mrow>
          <mn>2</mn>
        </mfrac>
        <mo>)</mo>
      </mrow>
      <mn>2</mn>
    </msup>
  </mstyle>
</math>
```

### PR DESCRIPTION
**Pull request by suleman-uzair**
This PR supports input field value conversion to the input type as the user changes the input type only on https://plurimath.org/demo.

closes #27

### CODE REVIEW

**Review by HassanAkbar — APPROVED** [review]

**Comment by ronaldtse** [comment]
@suleman-uzair How come `https://www.plurimath.org/plurimath-js/dist/index.js` is now missing?

**Comment by ronaldtse** [comment]
Not sure what has gone wrong?

**Comment by suleman-uzair** [comment]
> Not sure what has gone wrong?

@ronaldtse I'm not sure about it either; I'll look into it.

**Comment by ronaldtse** [comment]
> > Not sure what has gone wrong?
> 
> @ronaldtse I'm not sure about it either; I'll look into it.

I've fixed it, the submodule was missing. Also, we need plurimath-js to be built on all plurimath updates. This is missing?

**Pull request merged**
